version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    groups:
      aws-sdk-go-v2:
        patterns:
          - github.com/aws/aws-sdk-go-v2
          - github.com/aws/aws-sdk-go-v2/*
    schedule:
      interval: monthly
