---
name: CI
on:
  pull_request:
  push:
    branches: [main, 'release-*']
    tags: ['v*']

permissions:
  contents: read

jobs:
  test:
    name: Go tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - go_version: '1.25.x'
          - go_version: '1.26.x'
            latest: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: ${{ matrix.go_version }}
      - run: make test
      - run: make style
        if: matrix.latest
